import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#E9F1F0" },
  body: { padding: 16, paddingTop: 12 },
  scrollContent: { flexGrow: 1, paddingBottom: 120 },
  sectionTitle: {
    color: "#0F1E25",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    textAlign : "center"
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  cardTitle: {
    color: "#0F1E25",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 6,
  },
  cardSubtitle: {
    color: "#0F1E25",
    fontSize: 15,
    fontWeight: "700",
    opacity: 0.9,
  },
  badgesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
  },
  badgeCell: {
    width: "20%",
    paddingHorizontal: 6,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  badgePressable: { alignItems: "center", justifyContent: "center" },
  badgeMedal: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
  },
  tooltip: {
    position: "absolute",
    bottom: 64,
    maxWidth: 140,
    backgroundColor: "#111",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 6,
    alignItems: "center",
    zIndex: 2,
  },
  tooltipText: { color: "#fff", fontSize: 12, textAlign: "center" },
  tooltipCaret: {
    position: "absolute",
    bottom: -6,
    left: "50%",
    marginLeft: -6,
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 6,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: "#111",
  },
  calendarCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    overflow: "hidden",
  },
  calendar: {
    width: "100%",
    maxWidth: 320,
    alignSelf: "center",
    borderRadius: 20,
  },

  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 10,
    marginBottom: 8,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginRight: 16,
    marginBottom: 8,
  },
  colorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#ccc",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
  },
  legendText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0F1E25",
    opacity: 0.9,
  },
  content: { padding: 24, paddingTop: 36, paddingBottom: 42 },
  title: {
    color: "#0F1E25",
    fontSize: 25,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    color: "#4A5A61",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 18,
  },
  logo: { width: 190, height: 160, alignSelf: "center", marginTop: 6 },
  logoCaption: {
    textAlign: "center",
    color: "#0F1E25",
    fontWeight: "700",
    marginBottom: 16,
  },

  inputWrap: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
  },
  input: { color: "#0F1E25", fontSize: 14, paddingRight: 32 },

  helper: {
    textAlign: "center",
    color: "#0F1E25",
    opacity: 0.8,
    marginTop: 18,
    marginBottom: 6,
  },
  inputWrapDark: {
    backgroundColor: "#9BA2A6",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 6,
  },
  inputDark: { color: "#fff", fontSize: 14, paddingRight: 32, },
  inputError: { borderWidth: 1.2, borderColor: "#E63946" },
  errorText: {
    marginTop: 6,
    color: "#E63946",
    fontSize: 12,
    fontWeight: "600",
  },

  eye: { position: "absolute", right: 16, top: "50%", marginTop: 2 },

  btnPrimary: {
    marginTop: 22,
    backgroundColor: "#50C2C9",
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  btnText: { color: "#fff", fontSize: 16, fontWeight: "700" },

  forgotText: {
    textAlign: "center",
    color: "#6BBFC5",
    marginTop: 12,
    fontWeight: "600",
  },
  registerText: { textAlign: "center", marginTop: 18, color: "#0F1E25" },
  registerLink: { color: "#2CB1B8", fontWeight: "700" },

  bubbleLg: {
    position: "absolute",
    top: -80,
    left: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#CFEDEA",
  },
  bubbleSm: {
    position: "absolute",
    top: -10,
    left: 110,
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: "#BEE3E0",
  },

  inputErrorWrap: {
    borderWidth: 1.2,
    borderColor: "#E63946",
  },
  pickerWrapper: {
    justifyContent: "center",
  },

  pickerOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0,
  },

  pickerValueText: {
    color: "#0F1E25",
    fontSize: 14,
    paddingVertical: 4,
    textAlign: "left",
  },
  pickerChevron: {
    position: "absolute",
    right: 16,
    top: "50%",
    marginTop: -9,
  },
  shadowWrap: {
    borderRadius: 24,
    marginBottom: 4,
    shadowOffset: { width: 0, height: 6 },
  },
  btnPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  copy: {
    position: "absolute",
    right: 12,
    top: "50%",
    marginTop: -5,
    padding: 6,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  cardUserInfo: {
    marginLeft: 8,
  },
  ratingRow: {
    flexDirection: "row",
  },

  primaryButton: {
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  overviewTitle: {
    color: "#0F1E25",
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 6,
  },
  overviewSubtitle: {
    color: "#4A5A61",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 20,
    fontWeight: "700",
  },
  overviewDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: "#444",
    textAlign: "justify", 
    marginBottom: 120,
  },
  overviewButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    alignSelf: "center", 
    width: "60%",
    marginVertical: 16,
  },
  overviewButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
  },
});